[package]
name = "charon"
version = "0.1.2"
authors = ["Thomas Pöhlmann <thomaspoehlmann96@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { git = "https://github.com/clap-rs/clap/" }
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
dirs = "2.0.2"
log = "0.4.8"
env_logger = "0.7.1"
git2 = "0.12"
custom_error = "1.7.1"
colored = "1.9.3"
ctrlc = "3.1.4"
